### PR TITLE
Initial proposal drop

### LINKED ISSUE #3: [Feature request] Kafka to Kafka
The current implementation only supports tracing data from an http input.
Adding the ability to read data from Kafka would cover more market space.

### PR DESCRIPTION
**Pull request by eleduardo**
Fixes #3 

This is one approach @worldtiki can you check what you think...

These are a couple things to enhance
1) Assuming source is always Zipkin and sink is always Haystack, should it also do Zipkin-to-Zipkin?
2) Right now only one topic-to-topic is supported, but it could be coded to support N-to-1
3) Additional configurable stages could be added to the stream processing to add tags, transform tags, etc 

As of now no unit tests and I need to clean the rest of the config... before doing all that, any thoughts? Specially around the use of KStream, it is just so easy to use this...

### CODE REVIEW

**Comment by adriancole** [comment]
what would zipkin-zipkin be for? Is this an example of the proxy mentioned earlier?

https://github.com/HotelsDotCom/pitchfork/issues/3#issuecomment-432461616

One thing to keep in mind is that a very often use case is converting any supported format to a clean variant of v2.

For example, people standup a zipkin server, which can read all formats and then emit in clean v2. I *don't think* this codebase does it, yet, but a small change to the controller could ensure this. At that point, you would be serving a similar use case if there was a listener on one side zipkin(any) and a kafka emmission on the other (bundled v2, potentially partitioned on trace ID)

https://github.com/openzipkin/zipkin/blob/master/zipkin-junit/src/main/java/zipkin2/junit/ZipkinDispatcher.java#L42

cc @drolando @cwensel @narayuna @jcchavez

**Comment by adriancole** [comment]
cc also @devinsba and @llinder who have done pipelining with zipkin data in the past

**Comment by adriancole** [comment]
oh and @zeagord  heh (I'll stop :D)

**Comment by devinsba** [comment]
I concur with Adrian on the different formats thing. We write both JSON and Protobuf to our stream depending on how old the application is

**Comment by worldtiki** [comment]
The ability to output data to zipkin started as an accidental feature.
The original purpose was just to get the tracing data into Haystack but we felt the need to duplicate that data into Zipkin to be able to continue using Zipkin while we were tweaking the Haystack configs and setup.

That said, I do like the idea of "sanitizing" data or accepting multiple formats/versions and outputting to the v2 format.
Specially because we still use this feature (zipkin to zipkin) as a way to transport data (via http) between different environments/clusters/... until it finally reaches Haystack-Kafka. Using Kafka would be a much better way of doing this with the added benefit of opening new possibilities like controlling service abuse/etc.

I'm interested in hearing more opinions about using this as a proxy and we can totally continue the discussion here, but I don't think any of these changes should be done as part of this pull request. We can add value by merging this now, and separate the "_output to Zipkin-Kafka_" to be done later. Also, I don't want to abuse from @eleduardo's generosity 😛

**Comment by worldtiki** [comment]
Thanks Eduardo!
I'm merging this pr as is to unblock work in the RabbitMq ingress.
I'll raise a pr in the next couple of days to try and reuse the current forwarders (ie, replace kafka to kafka with kafka to many)

**Pull request merged**
